// Cadastro Geral de Campeões - Linha do Tempo Completa (2009 - 2025)
const LISTA_CAMPEOES = [
    // === LETRA A ===
    { nome: "Aatrox", imagem: "../default/icone_champions/aatrox.jpg", genero: "Homem", posicao: "Topo", classe: "Lutador", recurso: "Sem Mana", alcance: "Corpo-a-Corpo", regiao: "Runeterra, Shurima", ano: 2013 },
    { nome: "Ahri", imagem: "../default/icone_champions/ahri.jpg", genero: "Mulher", posicao: "Meio", classe: "Mago, Assassino", recurso: "Mana", alcance: "Longo Alcance", regiao: "Ionia", ano: 2011 },
    { nome: "Akali", imagem: "../default/icone_champions/akali.jpg", genero: "Mulher", posicao: "Topo, Meio", classe: "Assassino", recurso: "Energia", alcance: "Corpo-a-Corpo", regiao: "Ionia", ano: 2010 },
    { nome: "Akshan", imagem: "../default/icone_champions/akshan.jpg", genero: "Homem", posicao: "Meio, Topo", classe: "Atirador, Assassino", recurso: "Mana", alcance: "Longo Alcance", regiao: "Shurima", ano: 2021 },
    { nome: "Alistar", imagem: "../default/icone_champions/alistar.jpg", genero: "Homem", posicao: "Suporte", classe: "Tank, Suporte", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Runeterra", ano: 2009 },
    { nome: "Amumu", imagem: "../default/icone_champions/amumu.jpg", genero: "Homem", posicao: "Caçador, Suporte", classe: "Tank", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Shurima", ano: 2009 },
    { nome: "Ambessa", imagem: "../default/icone_champions/ambessa.jpg", genero: "Mulher", posicao: "Topo, Caçador", classe: "Lutador, Assassino", recurso: "Energia", alcance: "Corpo-a-Corpo", regiao: "Noxus", ano: 2024 },
    { nome: "Anivia", imagem: "../default/icone_champions/anivia.jpg", genero: "Mulher", posicao: "Meio", classe: "Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Freljord", ano: 2009 },
    { nome: "Annie", imagem: "../default/icone_champions/annie.jpg", genero: "Mulher", posicao: "Meio", classe: "Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Noxus", ano: 2009 },
    { nome: "Aphelios", imagem: "../default/icone_champions/aphelios.jpg", genero: "Homem", posicao: "Atirador", classe: "Atirador", recurso: "Mana", alcance: "Longo Alcance", regiao: "Targon", ano: 2019 },
    { nome: "Ashe", imagem: "../default/icone_champions/ashe.jpg", genero: "Mulher", posicao: "Atirador, Suporte", classe: "Atirador", recurso: "Mana", alcance: "Longo Alcance", regiao: "Freljord", ano: 2009 },
    { nome: "Aurelion Sol", imagem: "../default/icone_champions/aurelion.jpg", genero: "Homem", posicao: "Meio", classe: "Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Targon, Runeterra", ano: 2016 },
    { nome: "Azir", imagem: "../default/icone_champions/azir.jpg", genero: "Homem", posicao: "Meio", classe: "Mago, Atirador", recurso: "Mana", alcance: "Longo Alcance", regiao: "Shurima", ano: 2014 },

    // === LETRA B ===
    { nome: "Bard", imagem: "../default/icone_champions/bard.jpg", genero: "Outro", posicao: "Suporte", classe: "Suporte, Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Runeterra", ano: 2015 },
    { nome: "Bel'Veth", imagem: "../default/icone_champions/belveth.jpg", genero: "Mulher", posicao: "Caçador", classe: "Lutador", recurso: "Sem Mana", alcance: "Corpo-a-Corpo", regiao: "Vazio", ano: 2022 },
    { nome: "Blitzcrank", imagem: "../default/icone_champions/blitzcrank.jpg", genero: "Homem", posicao: "Suporte", classe: "Tank, Suporte", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Zaun", ano: 2009 },
    { nome: "Brand", imagem: "../default/icone_champions/brand.jpg", genero: "Homem", posicao: "Caçador, Meio, Suporte", classe: "Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Freljord, Runeterra", ano: 2011 },
    { nome: "Briar", imagem: "../default/icone_champions/briar.jpg", genero: "Mulher", posicao: "Caçador", classe: "Lutador, Assassino", recurso: "Saúde", alcance: "Corpo-a-Corpo", regiao: "Noxus", ano: 2023 },
    { nome: "Braum", imagem: "../default/icone_champions/braum.jpg", genero: "Homem", posicao: "Suporte", classe: "Tank, Suporte", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Freljord", ano: 2014 },

    // === LETRA C ===
    { nome: "Caitlyn", imagem: "../default/icone_champions/caitlyn.jpg", genero: "Mulher", posicao: "Atirador", classe: "Atirador", recurso: "Mana", alcance: "Longo Alcance", regiao: "Piltover", ano: 2011 },
    { nome: "Camille", imagem: "../default/icone_champions/camille.jpg", genero: "Mulher", posicao: "Topo, Suporte", classe: "Lutador", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Piltover", ano: 2016 },
    { nome: "Cassiopeia", imagem: "../default/icone_champions/cassiopeia.jpg", genero: "Mulher", posicao: "Meio", classe: "Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Noxus", ano: 2010 },
    { nome: "Cho'Gath", imagem: "../default/icone_champions/chogath.jpg", genero: "Homem", posicao: "Topo", classe: "Tank, Mago", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Vazio", ano: 2009 },
    { nome: "Corki", imagem: "../default/icone_champions/corki.jpg", genero: "Homem", posicao: "Meio, Atirador", classe: "Atirador", recurso: "Mana", alcance: "Longo Alcance", regiao: "Bandópolis", ano: 2009 },

    // === LETRA D ===
    { nome: "Darius", imagem: "../default/icone_champions/darius.jpg", genero: "Homem", posicao: "Topo", classe: "Lutador", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Noxus", ano: 2012 },
    { nome: "Diana", imagem: "../default/icone_champions/diana.jpg", genero: "Mulher", posicao: "Caçador, Meio", classe: "Lutador, Mago", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Targon", ano: 2012 },
    { nome: "Dr. Mundo", imagem: "../default/icone_champions/drmundo.jpg", genero: "Homem", posicao: "Topo, Caçador", classe: "Lutador, Tank", recurso: "Saúde", alcance: "Corpo-a-Corpo", regiao: "Zaun", ano: 2009 },
    { nome: "Draven", imagem: "../default/icone_champions/draven.jpg", genero: "Homem", posicao: "Atirador", classe: "Atirador", recurso: "Mana", alcance: "Longo Alcance", regiao: "Noxus", ano: 2012 },

    // === LETRA E ===
    { nome: "Ekko", imagem: "../default/icone_champions/ekko.jpg", genero: "Homem", posicao: "Caçador, Meio", classe: "Assassino, Mago", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Zaun", ano: 2015 },
    { nome: "Elise", imagem: "../default/icone_champions/elise.jpg", genero: "Mulher", posicao: "Caçador", classe: "Mago, Assassino", recurso: "Mana", alcance: "Corpo-a-Corpo, Longo Alcance", regiao: "Ilhas das Sombras, Noxus", ano: 2012 },
    { nome: "Evelynn", imagem: "../default/icone_champions/evelynn.jpg", genero: "Mulher", posicao: "Caçador", classe: "Assassino", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Runeterra", ano: 2009 },
    { nome: "Ezreal", imagem: "../default/icone_champions/ezreal.jpg", genero: "Homem", posicao: "Atirador", classe: "Atirador, Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Piltover", ano: 2010 },

    // === LETRAS F a G ===
    { nome: "Fiddlesticks", imagem: "../default/icone_champions/fiddlesticks.jpg", genero: "Outro", posicao: "Caçador", classe: "Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Runeterra", ano: 2009 },
    { nome: "Fiora", imagem: "../default/icone_champions/fiora.jpg", genero: "Mulher", posicao: "Topo", classe: "Lutador, Assassino", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Demacia", ano: 2012 },
    { nome: "Fizz", imagem: "../default/icone_champions/fizz.jpg", genero: "Homem", posicao: "Meio", classe: "Assassino", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Águas de Sentina", ano: 2011 },
    { nome: "Galio", imagem: "../default/icone_champions/galio.jpg", genero: "Homem", posicao: "Meio, Suporte", classe: "Tank, Mago", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Demacia", ano: 2010 },
    { nome: "Garen", imagem: "../default/icone_champions/garen.jpg", genero: "Homem", posicao: "Topo", classe: "Lutador, Tank", recurso: "Sem Mana", alcance: "Corpo-a-Corpo", regiao: "Demacia", ano: 2010 },
    { nome: "Gnar", imagem: "../default/icone_champions/gnar.jpg", genero: "Homem", posicao: "Topo", classe: "Lutador, Tank", recurso: "Fúria", alcance: "Corpo-a-Corpo, Longo Alcance", regiao: "Freljord", ano: 2014 },
    { nome: "Gragas", imagem: "../default/icone_champions/gragas.jpg", genero: "Homem", posicao: "Topo, Caçador, Meio", classe: "Lutador, Mago", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Freljord", ano: 2010 },
    { nome: "Graves", imagem: "../default/icone_champions/graves.jpg", genero: "Homem", posicao: "Caçador", classe: "Atirador", recurso: "Mana", alcance: "Longo Alcance", regiao: "Águas de Sentina", ano: 2011 },
    { nome: "Gangplank", imagem: "../default/icone_champions/gangplank.jpg", genero: "Homem", posicao: "Topo", classe: "Lutador", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Águas de Sentina", ano: 2009 },

    // === LETRAS H a I ===
    { nome: "Hecarim", imagem: "../default/icone_champions/hecarim.jpg", genero: "Homem", posicao: "Caçador", classe: "Lutador, Tank", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Ilhas das Sombras", ano: 2012 },
    { nome: "Heimerdinger", imagem: "../default/icone_champions/heimerdinger.jpg", genero: "Homem", posicao: "Meio, Topo", classe: "Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Piltover, Bandópolis", ano: 2009 },
    { nome: "Illaoi", imagem: "../default/icone_champions/illaoi.jpg", genero: "Mulher", posicao: "Topo", classe: "Lutador", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Águas de Sentina", ano: 2015 },
    { nome: "Irelia", imagem: "../default/icone_champions/irelia.jpg", genero: "Mulher", posicao: "Topo, Meio", classe: "Lutador, Assassino", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Ionia", ano: 2010 },
    { nome: "Ivern", imagem: "../default/icone_champions/ivern.jpg", genero: "Homem", posicao: "Caçador", classe: "Suporte, Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Ionia, Freljord", ano: 2016 },

    // === LETRA J ===
    { nome: "Janna", imagem: "../default/icone_champions/janna.jpg", genero: "Mulher", posicao: "Suporte", classe: "Suporte, Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Zaun", ano: 2009 },
    { nome: "Jarvan IV", imagem: "../default/icone_champions/jarvaniv.jpg", genero: "Homem", posicao: "Caçador", classe: "Lutador, Tank", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Demacia", ano: 2011 },
    { nome: "Jax", imagem: "../default/icone_champions/jax.jpg", genero: "Homem", posicao: "Topo, Caçador", classe: "Lutador", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Icathia, Runeterra", ano: 2009 },
    { nome: "Jayce", imagem: "../default/icone_champions/jayce.jpg", genero: "Homem", posicao: "Topo, Meio", classe: "Lutador, Atirador", recurso: "Mana", alcance: "Corpo-a-Corpo, Longo Alcance", regiao: "Piltover", ano: 2012 },
    { nome: "Jhin", imagem: "../default/icone_champions/jhin.jpg", genero: "Homem", posicao: "Atirador", classe: "Atirador, Assassino", recurso: "Mana", alcance: "Longo Alcance", regiao: "Ionia", ano: 2016 },
    { nome: "Jinx", imagem: "../default/icone_champions/jinx.jpg", genero: "Mulher", posicao: "Atirador", classe: "Atirador", recurso: "Mana", alcance: "Longo Alcance", regiao: "Zaun", ano: 2013 },

    // === LETRA K ===
    { nome: "Kai'Sa", imagem: "../default/icone_champions/kaisa.jpg", genero: "Mulher", posicao: "Atirador", classe: "Atirador, Assassino", recurso: "Mana", alcance: "Longo Alcance", regiao: "Vazio, Shurima", ano: 2018 },
    { nome: "Kalista", imagem: "../default/icone_champions/kalista.jpg", genero: "Mulher", posicao: "Atirador", classe: "Atirador", recurso: "Mana", alcance: "Longo Alcance", regiao: "Ilhas das Sombras, Camavor", ano: 2014 },
    { nome: "Karma", imagem: "../default/icone_champions/karma.jpg", genero: "Mulher", posicao: "Meio, Suporte", classe: "Mago, Suporte", recurso: "Mana", alcance: "Longo Alcance", regiao: "Ionia", ano: 2011 },
    { nome: "Karthus", imagem: "../default/icone_champions/karthus.jpg", genero: "Homem", posicao: "Caçador", classe: "Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Ilhas das Sombras", ano: 2009 },
    { nome: "Kassadin", imagem: "../default/icone_champions/kassadin.jpg", genero: "Homem", posicao: "Meio", classe: "Assassino, Mago", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Vazio, Shurima", ano: 2009 },
    { nome: "Katarina", imagem: "../default/icone_champions/katarina.jpg", genero: "Mulher", posicao: "Meio", classe: "Assassino, Mago", recurso: "Sem Mana", alcance: "Corpo-a-Corpo", regiao: "Noxus", ano: 2009 },
    { nome: "Kayle", imagem: "../default/icone_champions/kayle.jpg", genero: "Mulher", posicao: "Topo, Meio", classe: "Lutador, Mago", recurso: "Mana", alcance: "Corpo-a-Corpo, Longo Alcance", regiao: "Demacia, Targon", ano: 2009 },
    { nome: "Kayn", imagem: "../default/icone_champions/kayn.jpg", genero: "Homem", posicao: "Caçador", classe: "Lutador, Assassino", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Ionia, Noxus", ano: 2017 },
    { nome: "Kennen", imagem: "../default/icone_champions/kennen.jpg", genero: "Homem", posicao: "Topo", classe: "Mago, Atirador", recurso: "Energia", alcance: "Longo Alcance", regiao: "Ionia, Bandópolis", ano: 2010 },
    { nome: "Kha'Zix", imagem: "../default/icone_champions/khazix.jpg", genero: "Homem", posicao: "Caçador", classe: "Assassino", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Vazio", ano: 2012 },
    { nome: "Kindred", imagem: "../default/icone_champions/kindred.jpg", genero: "Outro", posicao: "Caçador", classe: "Atirador", recurso: "Mana", alcance: "Longo Alcance", regiao: "Runeterra", ano: 2015 },
    { nome: "Kled", imagem: "../default/icone_champions/kled.jpg", genero: "Homem", posicao: "Topo", classe: "Lutador", recurso: "Fúria", alcance: "Corpo-a-Corpo", regiao: "Noxus", ano: 2016 },
    { nome: "K'Sante", imagem: "../default/icone_champions/ksante.jpg", genero: "Homem", posicao: "Topo", classe: "Tank, Lutador", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Shurima", ano: 2022 },

    // === LETRA L ===
    { nome: "LeBlanc", imagem: "../default/icone_champions/leblanc.jpg", genero: "Mulher", posicao: "Meio", classe: "Assassino, Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Noxus", ano: 2010 },
    { nome: "Lee Sin", imagem: "../default/icone_champions/lee_sin.jpg", genero: "Homem", posicao: "Caçador", classe: "Lutador, Assassino", recurso: "Energia", alcance: "Corpo-a-Corpo", regiao: "Ionia", ano: 2011 },
    { nome: "Leona", imagem: "../default/icone_champions/leona.jpg", genero: "Mulher", posicao: "Suporte", classe: "Tank, Suporte", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Targon", ano: 2011 },
    { nome: "Lillia", imagem: "../default/icone_champions/lillia.jpg", genero: "Mulher", posicao: "Caçador", classe: "Mago, Lutador", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Ionia", ano: 2020 },
    { nome: "Lissandra", imagem: "../default/icone_champions/lissandra.jpg", genero: "Mulher", posicao: "Meio", classe: "Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Freljord", ano: 2013 },
    { nome: "Lucian", imagem: "../default/icone_champions/lucian.jpg", genero: "Homem", posicao: "Atirador", classe: "Atirador", recurso: "Mana", alcance: "Longo Alcance", regiao: "Demacia, Ilhas das Sombras", ano: 2013 },
    { nome: "Lulu", imagem: "../default/icone_champions/lulu.jpg", genero: "Mulher", posicao: "Suporte", classe: "Suporte, Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Bandópolis", ano: 2012 },
    { nome: "Lux", imagem: "../default/icone_champions/lux.jpg", genero: "Mulher", posicao: "Meio, Suporte", classe: "Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Demacia", ano: 2010 },

    // === LETRA M ===
    { nome: "Malphite", imagem: "../default/icone_champions/malphite.jpg", genero: "Homem", posicao: "Topo, Meio", classe: "Tank, Mago", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Ixtal", ano: 2009 },
    { nome: "Malzahar", imagem: "../default/icone_champions/malzahar.jpg", genero: "Homem", posicao: "Meio", classe: "Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Shurima, Vazio", ano: 2010 },
    { nome: "Maokai", imagem: "../default/icone_champions/maokai.jpg", genero: "Homem", posicao: "Suporte, Caçador, Topo", classe: "Tank, Suporte", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Ilhas das Sombras", ano: 2011 },
    { nome: "Master Yi", imagem: "../default/icone_champions/master_yi.jpg", genero: "Homem", posicao: "Caçador", classe: "Assassino, Lutador", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Ionia", ano: 2009 },
    { nome: "Mel", imagem: "../default/icone_champions/mel.jpg", genero: "Mulher", posicao: "Meio", classe: "Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Piltover, Noxus", ano: 2025 },
    { nome: "Milio", imagem: "../default/icone_champions/milio.jpg", genero: "Homem", posicao: "Suporte", classe: "Suporte, Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Ixtal", ano: 2023 },
    { nome: "Miss Fortune", imagem: "../default/icone_champions/missfortune.jpg", genero: "Mulher", posicao: "Atirador", classe: "Atirador", recurso: "Mana", alcance: "Longo Alcance", regiao: "Águas de Sentina", ano: 2010 },
    { nome: "Mordekaiser", imagem: "../default/icone_champions/mordekaiser.jpg", genero: "Homem", posicao: "Topo", classe: "Lutador", recurso: "Escudo", alcance: "Corpo-a-Corpo", regiao: "Noxus", ano: 2010 },
    { nome: "Morgana", imagem: "../default/icone_champions/morgana.jpg", genero: "Mulher", posicao: "Meio, Suporte", classe: "Mago, Suporte", recurso: "Mana", alcance: "Longo Alcance", regiao: "Demacia, Targon", ano: 2009 },

    // === LETRAS N a O ===
    { nome: "Naafiri", imagem: "../default/icone_champions/naafiri.jpg", genero: "Mulher", posicao: "Meio", classe: "Assassino", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Shurima", ano: 2023 },
    { nome: "Nami", imagem: "../default/icone_champions/nami.jpg", genero: "Mulher", posicao: "Suporte", classe: "Suporte, Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Águas de Sentina", ano: 2012 },
    { nome: "Nasus", imagem: "../default/icone_champions/nasus.jpg", genero: "Homem", posicao: "Topo", classe: "Lutador, Tank", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Shurima", ano: 2009 },
    { nome: "Nautilus", imagem: "../default/icone_champions/nautilus.jpg", genero: "Homem", posicao: "Suporte", classe: "Tank, Suporte", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Águas de Sentina", ano: 2012 },
    { nome: "Nidalee", imagem: "../default/icone_champions/nidalee.jpg", genero: "Mulher", posicao: "Caçador", classe: "Assassino, Mago", recurso: "Mana", alcance: "Corpo-a-Corpo, Longo Alcance", regiao: "Ixtal", ano: 2009 },
    { nome: "Nilah", imagem: "../default/icone_champions/nilah.jpg", genero: "Mulher", posicao: "Atirador", classe: "Lutador, Assassino", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Águas de Sentina", ano: 2022 },
    { nome: "Nocturne", imagem: "../default/icone_champions/nocturne.jpg", genero: "Homem", posicao: "Caçador", classe: "Assassino, Lutador", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Runeterra", ano: 2011 },
    { nome: "Olaf", imagem: "../default/icone_champions/olaf.jpg", genero: "Homem", posicao: "Topo, Caçador", classe: "Lutador", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Freljord", ano: 2010 },
    { nome: "Orianna", imagem: "../default/icone_champions/orianna.jpg", genero: "Mulher", posicao: "Meio", classe: "Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Piltover", ano: 2011 },
    { nome: "Ornn", imagem: "../default/icone_champions/ornn.jpg", genero: "Homem", posicao: "Topo", classe: "Tank, Lutador", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Freljord", ano: 2017 },

    // === LETRA P a R ===
    { nome: "Pantheon", imagem: "../default/icone_champions/pantheon.jpg", genero: "Homem", posicao: "Topo, Meio, Suporte", classe: "Lutador, Assassino", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Targon", ano: 2010 },
    { nome: "Poppy", imagem: "../default/icone_champions/poppy.jpg", genero: "Mulher", posicao: "Topo, Caçador, Suporte", classe: "Tank, Lutador", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Demacia, Bandópolis", ano: 2010 },
    { nome: "Pyke", imagem: "../default/icone_champions/pyke.jpg", genero: "Homem", posicao: "Suporte", classe: "Assassino, Suporte", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Águas de Sentina", ano: 2018 },
    { nome: "Qiyana", imagem: "../default/icone_champions/qiyana.jpg", genero: "Mulher", posicao: "Meio, Caçador", classe: "Assassino", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Ixtal", ano: 2019 },
    { nome: "Quinn", imagem: "../default/icone_champions/quinn.jpg", genero: "Mulher", posicao: "Topo", classe: "Atirador, Assassino", recurso: "Mana", alcance: "Longo Alcance", regiao: "Demacia", ano: 2013 },
    { nome: "Rakan", imagem: "../default/icone_champions/rakan.jpg", genero: "Homem", posicao: "Suporte", classe: "Suporte, Tank", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Ionia", ano: 2017 },
    { nome: "Rammus", imagem: "../default/icone_champions/rammus.jpg", genero: "Homem", posicao: "Caçador", classe: "Tank", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Shurima", ano: 2009 },
    { nome: "Rell", imagem: "../default/icone_champions/rell.jpg", genero: "Mulher", posicao: "Suporte", classe: "Tank, Suporte", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Noxus", ano: 2020 },
    { nome: "Renata Glasc", imagem: "../default/icone_champions/renata.jpg", genero: "Mulher", posicao: "Suporte", classe: "Suporte, Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Zaun", ano: 2022 },
    { nome: "Renekton", imagem: "../default/icone_champions/renekton.jpg", genero: "Homem", posicao: "Topo", classe: "Lutador", recurso: "Fúria", alcance: "Corpo-a-Corpo", regiao: "Shurima", ano: 2011 },
    { nome: "Rengar", imagem: "../default/icone_champions/rengar.jpg", genero: "Homem", posicao: "Caçador, Topo", classe: "Assassino, Lutador", recurso: "Fúria", alcance: "Corpo-a-Corpo", regiao: "Ixtal", ano: 2012 },
    { nome: "Riven", imagem: "../default/icone_champions/riven.jpg", genero: "Mulher", posicao: "Topo", classe: "Lutador, Assassino", recurso: "Sem Mana", alcance: "Corpo-a-Corpo", regiao: "Noxus", ano: 2011 },
    { nome: "Rumble", imagem: "../default/icone_champions/rumble.jpg", genero: "Homem", posicao: "Topo, Meio", classe: "Lutador, Mago", recurso: "Aquecimento", alcance: "Corpo-a-Corpo", regiao: "Bandópolis", ano: 2011 },
    { nome: "Ryze", imagem: "../default/icone_champions/ryze.jpg", genero: "Homem", posicao: "Meio, Topo", classe: "Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Runeterra", ano: 2009 },

    // === LETRA S ===
    { nome: "Samira", imagem: "../default/icone_champions/samira.jpg", genero: "Mulher", posicao: "Atirador", classe: "Atirador, Assassino", recurso: "Mana", alcance: "Longo Alcance", regiao: "Noxus, Shurima", ano: 2020 },
    { nome: "Sejuani", imagem: "../default/icone_champions/sejuani.jpg", genero: "Mulher", posicao: "Caçador", classe: "Tank", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Freljord", ano: 2012 },
    { nome: "Senna", imagem: "../default/icone_champions/senna.jpg", genero: "Mulher", posicao: "Suporte, Atirador", classe: "Atirador, Suporte", recurso: "Mana", alcance: "Longo Alcance", regiao: "Ilhas das Sombras", ano: 2019 },
    { nome: "Seraphine", imagem: "../default/icone_champions/seraphine.jpg", genero: "Mulher", posicao: "Suporte, Meio", classe: "Mago, Suporte", recurso: "Mana", alcance: "Longo Alcance", regiao: "Piltover, Zaun", ano: 2020 },
    { nome: "Sett", imagem: "../default/icone_champions/sett.jpg", genero: "Homem", posicao: "Topo", classe: "Lutador, Tank", recurso: "Firmeza", alcance: "Corpo-a-Corpo", regiao: "Ionia", ano: 2020 },
    { nome: "Shaco", imagem: "../default/icone_champions/shaco.jpg", genero: "Homem", posicao: "Caçador, Suporte", classe: "Assassino", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Runeterra", ano: 2009 },
    { nome: "Shen", imagem: "../default/icone_champions/shen.jpg", genero: "Homem", posicao: "Topo, Suporte", classe: "Tank, Suporte", recurso: "Energia", alcance: "Corpo-a-Corpo", regiao: "Ionia", ano: 2010 },
    { nome: "Shyvana", imagem: "../default/icone_champions/shyvana.jpg", genero: "Mulher", posicao: "Caçador", classe: "Lutador, Tank", recurso: "Fúria", alcance: "Corpo-a-Corpo", regiao: "Demacia", ano: 2011 },
    { nome: "Singed", imagem: "../default/icone_champions/singed.jpg", genero: "Homem", posicao: "Topo", classe: "Tank, Lutador", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Zaun", ano: 2009 },
    { nome: "Sion", imagem: "../default/icone_champions/sion.jpg", genero: "Homem", posicao: "Topo", classe: "Tank, Lutador", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Noxus", ano: 2009 },
    { nome: "Sivir", imagem: "../default/icone_champions/sivir.jpg", genero: "Mulher", posicao: "Atirador", classe: "Atirador", recurso: "Mana", alcance: "Longo Alcance", regiao: "Shurima", ano: 2009 },
    { nome: "Skarner", imagem: "../default/icone_champions/skarner.jpg", genero: "Homem", posicao: "Caçador, Topo", classe: "Tank, Lutador", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Ixtal", ano: 2011 },
    { nome: "Smolder", imagem: "../default/icone_champions/smolder.jpg", genero: "Homem", posicao: "Atirador", classe: "Atirador", recurso: "Mana", alcance: "Longo Alcance", regiao: "Camavor", ano: 2024 },
    { nome: "Sona", imagem: "../default/icone_champions/sona.jpg", genero: "Mulher", posicao: "Suporte", classe: "Suporte, Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Demacia, Ionia", ano: 2010 },
    { nome: "Soraka", imagem: "../default/icone_champions/soraka.jpg", genero: "Mulher", posicao: "Suporte", classe: "Suporte, Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Targon, Ionia", ano: 2009 },
    { nome: "Swain", imagem: "../default/icone_champions/swain.jpg", genero: "Homem", posicao: "Meio, Suporte", classe: "Mago, Lutador", recurso: "Mana", alcance: "Longo Alcance", regiao: "Noxus", ano: 2010 },
    { nome: "Sylas", imagem: "../default/icone_champions/sylas.jpg", genero: "Homem", posicao: "Meio, Topo", classe: "Mago, Lutador", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Demacia", ano: 2019 },
    { nome: "Syndra", imagem: "../default/icone_champions/syndra.jpg", genero: "Mulher", posicao: "Meio", classe: "Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Ionia", ano: 2012 },

    // === LETRA T a V ===
    { nome: "Tahm Kench", imagem: "../default/icone_champions/tahmkench.jpg", genero: "Homem", posicao: "Suporte, Topo", classe: "Tank, Suporte", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Águas de Sentina", ano: 2015 },
    { nome: "Taliyah", imagem: "../default/icone_champions/taliyah.jpg", genero: "Mulher", posicao: "Caçador, Meio", classe: "Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Shurima", ano: 2016 },
    { nome: "Talon", imagem: "../default/icone_champions/talon.jpg", genero: "Homem", posicao: "Meio, Caçador", classe: "Assassino", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Noxus", ano: 2011 },
    { nome: "Taric", imagem: "../default/icone_champions/taric.jpg", genero: "Homem", posicao: "Suporte", classe: "Suporte, Tank", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Targon, Demacia", ano: 2009 },
    { nome: "Teemo", imagem: "../default/icone_champions/teemo.jpg", genero: "Homem", posicao: "Topo", classe: "Mago, Atirador", recurso: "Mana", alcance: "Longo Alcance", regiao: "Bandópolis", ano: 2009 },
    { nome: "Thresh", imagem: "../default/icone_champions/thresh.jpg", genero: "Homem", posicao: "Suporte", classe: "Suporte, Tank", recurso: "Mana", alcance: "Longo Alcance", regiao: "Ilhas das Sombras", ano: 2013 },
    { nome: "Tristana", imagem: "../default/icone_champions/tristana.jpg", genero: "Mulher", posicao: "Atirador, Meio", classe: "Atirador", recurso: "Mana", alcance: "Longo Alcance", regiao: "Bandópolis", ano: 2009 },
    { nome: "Trundle", imagem: "../default/icone_champions/trundle.jpg", genero: "Homem", posicao: "Topo, Caçador", classe: "Lutador, Tank", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Freljord", ano: 2010 },
    { nome: "Tryndamere", imagem: "../default/icone_champions/tryndamere.jpg", genero: "Homem", posicao: "Topo", classe: "Lutador, Assassino", recurso: "Fúria", alcance: "Corpo-a-Corpo", regiao: "Freljord", ano: 2009 },
    { nome: "Twisted Fate", imagem: "../default/icone_champions/twistedfate.jpg", genero: "Homem", posicao: "Meio, Atirador", classe: "Mago, Atirador", recurso: "Mana", alcance: "Longo Alcance", regiao: "Águas de Sentina", ano: 2009 },
    { nome: "Twitch", imagem: "../default/icone_champions/twitch.jpg", genero: "Homem", posicao: "Atirador", classe: "Atirador, Assassino", recurso: "Mana", alcance: "Longo Alcance", regiao: "Zaun", ano: 2009 },
    { nome: "Udyr", imagem: "../default/icone_champions/udyr.jpg", genero: "Homem", posicao: "Caçador, Topo", classe: "Lutador, Tank", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Freljord, Ionia", ano: 2009 },
    { nome: "Urgot", imagem: "../default/icone_champions/urgot.jpg", genero: "Homem", posicao: "Topo", classe: "Lutador, Tank", recurso: "Mana", alcance: "Longo Alcance", regiao: "Zaun, Noxus", ano: 2010 },
    { nome: "Varus", imagem: "../default/icone_champions/varus.jpg", genero: "Homem", posicao: "Atirador, Meio", classe: "Atirador, Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Ionia, Shurima", ano: 2012 },
    { nome: "Vayne", imagem: "../default/icone_champions/vayne.jpg", genero: "Mulher", posicao: "Atirador, Topo", classe: "Atirador, Assassino", recurso: "Mana", alcance: "Longo Alcance", regiao: "Demacia", ano: 2011 },
    { nome: "Veigar", imagem: "../default/icone_champions/veigar.jpg", genero: "Homem", posicao: "Meio", classe: "Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Bandópolis, Noxus", ano: 2009 },
    { nome: "Vel'Koz", imagem: "../default/icone_champions/velkoz.jpg", genero: "Homem", posicao: "Meio, Suporte", classe: "Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Vazio", ano: 2014 },
    { nome: "Vex", imagem: "../default/icone_champions/vex.jpg", genero: "Mulher", posicao: "Meio", classe: "Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Ilhas das Sombras, Bandópolis", ano: 2021 },
    { nome: "Vi", imagem: "../default/icone_champions/vi.jpg", genero: "Mulher", posicao: "Caçador", classe: "Lutador, Assassino", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Piltover, Zaun", ano: 2012 },
    { nome: "Viego", imagem: "../default/icone_champions/viego.jpg", genero: "Homem", posicao: "Caçador", classe: "Lutador, Assassino", recurso: "Sem Mana", alcance: "Corpo-a-Corpo", regiao: "Ilhas das Sombras, Camavor", ano: 2021 },
    { nome: "Viktor", imagem: "../default/icone_champions/viktor.jpg", genero: "Homem", posicao: "Meio", classe: "Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Zaun", ano: 2011 },
    { nome: "Vladimir", imagem: "../default/icone_champions/vladimir.jpg", genero: "Homem", posicao: "Meio, Topo", classe: "Mago, Tank", recurso: "Sem Mana", alcance: "Longo Alcance", regiao: "Noxus, Camavor", ano: 2010 },
    { nome: "Volibear", imagem: "../default/icone_champions/volibear.jpg", genero: "Homem", posicao: "Topo, Caçador", classe: "Lutador, Tank", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Freljord", ano: 2011 },

    // === LETRAS W a Z ===
    { nome: "Warwick", imagem: "../default/icone_champions/warwick.jpg", genero: "Homem", posicao: "Caçador, Topo", classe: "Lutador, Tank", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Zaun", ano: 2009 },
    { nome: "Wukong", imagem: "../default/icone_champions/wukong.jpg", genero: "Homem", posicao: "Topo, Caçador", classe: "Lutador, Tank", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Ionia", ano: 2011 },
    { nome: "Xayah", imagem: "../default/icone_champions/xayah.jpg", genero: "Mulher", posicao: "Atirador", classe: "Atirador", recurso: "Mana", alcance: "Longo Alcance", regiao: "Ionia", ano: 2017 },
    { nome: "Xerath", imagem: "../default/icone_champions/xerath.jpg", genero: "Homem", posicao: "Meio, Suporte", classe: "Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Shurima", ano: 2011 },
    { nome: "Xin Zhao", imagem: "../default/icone_champions/xinzhao.jpg", genero: "Homem", posicao: "Caçador", classe: "Lutador, Tank", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Demacia, Noxus", ano: 2010 },
    { nome: "Yasuo", imagem: "../default/icone_champions/yasuo.jpg", genero: "Homem", posicao: "Meio, Atirador", classe: "Lutador, Assassino", recurso: "Fluxo", alcance: "Corpo-a-Corpo", regiao: "Ionia", ano: 2013 },
    { nome: "Yone", imagem: "../default/icone_champions/yone.jpg", genero: "Homem", posicao: "Topo, Meio", classe: "Assassino, Lutador", recurso: "Sem Mana", alcance: "Corpo-a-Corpo", regiao: "Ionia", ano: 2020 },
    { nome: "Yorick", imagem: "../default/icone_champions/yorick.jpg", genero: "Homem", posicao: "Topo", classe: "Lutador, Tank", recurso: "Mana", alcance: "Corpo-a-Corpo", regiao: "Ilhas das Sombras", ano: 2011 },
    { nome: "Yuumi", imagem: "../default/icone_champions/yuumi.jpg", genero: "Mulher", posicao: "Suporte", classe: "Suporte, Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Bandópolis", ano: 2019 },
    { nome: "Zac", imagem: "../default/icone_champions/zac.jpg", genero: "Homem", posicao: "Caçador, Topo", classe: "Tank", recurso: "Saúde", alcance: "Corpo-a-Corpo", regiao: "Zaun", ano: 2013 },
    { nome: "Zed", imagem: "../default/icone_champions/zed.jpg", genero: "Homem", posicao: "Meio", classe: "Assassino", recurso: "Energia", alcance: "Corpo-a-Corpo", regiao: "Ionia", ano: 2012 },
    { nome: "Zeri", imagem: "../default/icone_champions/zeri.jpg", genero: "Mulher", posicao: "Atirador", classe: "Atirador", recurso: "Mana", alcance: "Longo Alcance", regiao: "Zaun", ano: 2022 },
    { nome: "Ziggs", imagem: "../default/icone_champions/ziggs.jpg", genero: "Homem", posicao: "Meio, Atirador", classe: "Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Zaun, Bandópolis", ano: 2012 },
    { nome: "Zilean", imagem: "../default/icone_champions/zilean.jpg", genero: "Homem", posicao: "Suporte, Meio", classe: "Suporte, Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Runeterra", ano: 2009 },
    { nome: "Zoe", imagem: "../default/icone_champions/zoe.jpg", genero: "Mulher", posicao: "Meio", classe: "Mago", recurso: "Mana", alcance: "Longo Alcance", regiao: "Targon", ano: 2017 },
    { nome: "Zyra", imagem: "../default/icone_champions/zyra.jpg", genero: "Mulher", posicao: "Suporte", classe: "Mago, Suporte", recurso: "Mana", alcance: "Longo Alcance", regiao: "Ixtal", ano: 2012 }
];